### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#242]
I tried to run the `collect.py` script on a new machine (gamone) and got this error, after it had processed about 1200 files:

```
2017-02-06 10:16:59 gamone root[9744] INFO Translating /usgs/data2/rsignell/stellwagen/usgs-cmg-portal/woods_hole_obs_data/download/MBAY_IWAVE/5351tcp-a.nc into CF1.6 format: /usgs/data2/rsignell/stellwagen/CF-1.6/MBAY_IWAVE/5351tcp-a.nc
2017-02-06 10:16:59 gamone root[9744] ERROR Error. Skipping /usgs/data2/rsignell/stellwagen/usgs-cmg-portal/woods_hole_obs_data/download/MBAY_IWAVE/5352adc-a.nc.
Traceback (most recent call last):
  File "collect.py", line 430, in main
    shutil.copy(down_file, temp_file)
  File "/home/rsignell/miniconda3/envs/CONVERT-WH/lib/python3.5/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/rsignell/miniconda3/envs/CONVERT-WH/lib/python3.5/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
OSError: [Errno 24] Too many open files: '/tmp/cmg_collectorajrkimc3nc'
```

**Comment by rsignell-usgs** [comment]
I gchatted @kwilcox that `ulimit -n` was reporting back `1024`. 

He replied:

> thats pretty low
> i usually set to 65k. I'm relying on pythons garbage collection for the main object
> going to be impossible to reproduce

I fixed the problem by editing `/etc/security/limits.conf`, adding these lines:
```
root hard nofile 81920
root soft nofile 81920
@users hard nofile 81920
@users soft nofile 81920
```
and rebooted.      

Now `ulimit -n` reports back `81920`
