### ISSUE TITLE
convert.py not reading successfully

### ISSUE THREAD

**Issue by emontgomery-usgs** [USGS-CMG/usgs-cmg-portal#56]
Piease let me know what I'm doing wrong.

I have the (ioos) in my prompt so think I have the correct environment.  Then I  cd'd into woods_hole_obs_data and issue this command:
$ python collect.py --projects MAMALA_BAY --folder /usgs/data2/emontgomery/stellwagen/Data/MAMALA_BAY --output=../../CF-1.6/

and it gets these errors:
```
2015-04-07 11:31:04 gam root[1989] ERROR Error. Skipping /usgs/data2/emontgomery/stellwagen/Data/MAMALA_BAY/4813att-a1h.cdf.
Traceback (most recent call last):
  File "collect.py", line 437, in main
    project_name, _ = tmpnc.id.split("/")
  File "netCDF4.pyx", line 1934, in netCDF4.Dataset.__getattr__ (netCDF4.c:27282)
  File "netCDF4.pyx", line 1879, in netCDF4.Dataset.getncattr (netCDF4.c:26363)
  File "netCDF4.pyx", line 912, in netCDF4._get_att (netCDF4.c:16548)
AttributeError: NetCDF: Attribute not found
2015-04-07 11:31:04 gam root[1989] ERROR Error. Skipping /usgs/data2/emontgomery/stellwagen/Data/MAMALA_BAY/4813tct.cdf.
Traceback (most recent call last):
  File "collect.py", line 437, in main
    project_name, _ = tmpnc.id.split("/")
  File "netCDF4.pyx", line 1934, in netCDF4.Dataset.__getattr__ (netCDF4.c:27282)
  File "netCDF4.pyx", line 1879, in netCDF4.Dataset.getncattr (netCDF4.c:26363)
  File "netCDF4.pyx", line 912, in netCDF4._get_att (netCDF4.c:16548)
AttributeError: NetCDF: Attribute not found
```

**Comment by emontgomery-usgs** [comment]
Well, it works if I have "download" in the command and use the defaults:
$ python collect.py --projects MAMALA_BAY --download --output=../../CF-1.6/
appears to work and generates these messages:
```
2015-04-07 11:45:12 gam root[2108] INFO Translating /usgs/data2/emontgomery/stellwagen/usgs-cmg-portal/woods_hole_obs_data/download/4813-a.cdf into CF1.6 format: /usgs/data2/emontgomery/stellwagen/CF-1.6/MAMALA_BAY/4813-a.cdf
2015-04-07 11:45:12 gam root[2108] DEBUG Could not find CF mapping for EPIC code 624
2015-04-07 11:45:12 gam root[2108] DEBUG Could not find CF mapping for EPIC code 624
2015-04-07 11:45:12 gam root[2108] DEBUG Could not find CF mapping for EPIC code 4006
2015-04-07 11:45:13 gam root[2108] INFO Translating /usgs/data2/emontgomery/stellwagen/usgs-cmg-portal/woods_hole_obs_data/download/4813att-a.cdf into CF1.6 format: /usgs/data2/emontgomery/stellwagen/CF-1.6/MAMALA_BAY/4813att-a.cdf
```

**Comment by rsignell-usgs** [comment]
@kwilcox , since @emontgomery-usgs didn't specify a folder to download files from, it must be getting this from the last column of the CSV file, right:?
https://raw.githubusercontent.com/USGS-CMG/usgs-cmg-portal/master/woods_hole_obs_data/project_metadata.csv

**Comment by emontgomery-usgs** [comment]
when I used the --download default, it made a directory called "download" in woods_hole_obs_data that has the files it got from the server.  Isn't the purpose of the --folders option (without --download) to point to a local directory and process data from there?

**Comment by emontgomery-usgs** [comment]
The reason you have to download initially is that an attribute is added to each file: project_name.  The directory contents will look exactly the same, but each file will have one more attribute.

*Just do the download, at least once to refresh the contents of the Data directory.*
